### ISSUE TITLE
Add sensible defaults for the maximum output degree

### ISSUE THREAD

**Issue by Enchufa2** [IBiDat/nn2poly#48]
E.g. 2?

Also, the default should be `q_taylor_vector=8` instead of `NULL` and more explanation is required in the documentation as to why this value is needed.

**Comment by Enchufa2** [comment]
BTW, do we have any check for whether the `q_taylor_vector` is appropriate for the `forced_max_Q`?

**Comment by moralapablo** [comment]
Yes, fixing the default value for the maximum polynomial order to be 2 by default should be enough as it captures interactions pairwise and is the safest value for an user that forgets to set the maximum in a network with many layers.

> BTW, do we have any check for whether the q_taylor_vector is appropriate for the forced_max_Q?

- Regarding the relation between `forced_max_Q` and `q_taylor_vector`, current implementation sets `forced_max_Q` as the order of the final polynomial unless the product of terms in `q_taylor_vector` is lower than `forced_max_Q`. Example: if `forced_max_Q`=5 and `q_taylor_vector` = (2,2,1), the product of taylor orders is 4 and thus the final polynomial order would be 4<5. This is intended behavior as `forced_max_Q` acts as a maximum for the polynomial order but does not force it  to reach said value. Forcing the polynomial to reach `forced_max_Q`=5 in the previous example would be ambiguous as `q_taylor_vector` = (3,2,1) would allow it do it but also `q_taylor_vector` = (2,3,1) and therefore there is no unique way of doing so.
	- Anyway, this situation might never arise in practice, but maybe showing a warning saying that `forced_max_Q` was not reached would be enough?

**Comment by moralapablo** [comment]
In general, the last layer would be linear and the taylor value then would be 1 at that output layer. However the method is programmed to be able to work also when there is a non linear activation function at the output layer, so we should keep the possibility to change that parameter to be different from 1.

Maybe a solution could be to have two options:
- Set the full vector `taylor_orders=c(8,8,1)`, including the value for the output layer, only for advanced users that would need to use 1 as the last value if the output is linear and any other value if it is not.
- Set only one numeric value for the Taylor series (e.g., `taylor_orders=8`), which would be automatically set for all non linear layers

**Comment by Enchufa2** [comment]
Ok!
