### ISSUE TITLE
Rethink nn2poly arguments

### ISSUE THREAD

**Issue by Enchufa2** [IBiDat/nn2poly#49]
The current signature is:

```r
nn2poly(
  object,
  q_taylor_vector = NULL,
  all_partitions = NULL,
  store_coeffs = FALSE,
  forced_max_Q = NULL,
  ...
)
```

which I don't think is user-friendly due to the order and naming.

### Reordering

The most important arguments for the user should come first. Please correct me if I'm wrong, but here `q_taylor_vector` and `all_partitions` are mainly internal knobs for advanced users, and it's unlikely that an average user would like (or know how) to change them. I see `forced_max_Q` as the main parameter that a user may want to change, so it should come first.

But then, I'm not so sure if `store_coeffs` should be before or after `q_taylor_vector`. I see it as more likely to be understood and used by an average user, but then `q_taylor_vector` is more related to `forced_max_Q`, so that's a strong argument for putting them together.

Finally, the `all_partitions` argument should eventually disappear (see #50), so we should move it **after the dots**.

### Interaction between arguments

- Is there a check for whether the `q_taylor_vector` is appropriate for the `forced_max_Q`? (see #48).
- Also, the user should be able to specify a `q_taylor_vector` as a vector, one value per layer, or a single value that applies to all layers.
- Does `forced_max_Q` apply to the output of the layers if `store_coeffs=TRUE`? Should it?

### Renaming

The current argument names are hard to understand unless you know the method very well. We should take a step back here and propose something that does not necessarily require to read the paper. ;-) We could use some brainstorming here. Let me start:

- `forced_max_Q` -> `degree_out`?
- `q_taylor_vector` -> `degree_layers`?
- `store_coeffs` -> `store_layers`?
- `all_partitions` -> same?

**Comment by moralapablo** [comment]
Sure, we need to make it more user friendly and not so dependent on having read the methodological paper. Some comments on each aspect:

### Reordering and renaming
- `forced_max_Q`: I agree that  this should be the first argument and also renamed to something shorter: `max_degree` or  `max_order`. I think that keeping the "max" is clear about how the user is limiting the total polynomial order/degree with this parameter, while `degree_out`  might not be so clear about this? 
	- Also, while order and degree are equivalent in this context, I think that for consistency we should stick with "order", instead of "degree", terminology  through the code as the theoretical nn2poly paper always uses "order" and never "degree". In other mathematical contexts, order could be a bit ambiguous (see [this](https://math.stackexchange.com/questions/3323294/degree-and-order-of-a-polynomial)), but I think that here is not the case.
- `store_coeffs`: This one should be the second argument as the average user might want to explore the internal polynomials in some cases, while the `q_taylor_vector` is more of an advanced option. Could be renamed to `store_layers` or `keep_layers`. 
- `q_taylor_vector`: Renaming it to `degree_layers` might be confusing as the output polynomial at each layer order/degree will not have the same order as the specified in this argument. An example: a NN with 2 hidden layers with $Q_{max}$=3 but `q_taylor_vector` = (8,8,1), would have all internal layers polynomial's order/degree limited to 5. Maybe something simpler like `taylor_orders`? In any case this argument might really never be used in practical cases aside from some performance checks on the method?
- `all_partitions` the name could remain the same and yes, it should eventually disappear.

### Interaction between arguments

> Is there a check for whether the q_taylor_vector is appropriate for the forced_max_Q? (see https://github.com/IBiDat/nn2poly/issues/48).

- Regarding the relation between `forced_max_Q` and `q_taylor_vector`, current implementation sets `forced_max_Q` as the order of the final polynomial unless the product of terms in `q_taylor_vector` is lower than `forced_max_Q`. Example: if `forced_max_Q`=5 and `q_taylor_vector` = (2,2,1), the product of taylor orders is 4 and thus the final polynomial order would be 4<5. This is intended behavior as `forced_max_Q` acts as a maximum for the polynomial order but does not force it  to reach said value. Forcing the polynomial to reach `forced_max_Q`=5 in the previous example would be ambiguous as `q_taylor_vector` = (3,2,1) would allow it do it but also `q_taylor_vector` = (2,3,1) and therefore there is no unique way of doing so.
	- Anyway, this situation might never arise in practice, but maybe showing a warning saying that `forced_max_Q` was not reached would be enough?

> Also, the user should be able to specify a q_taylor_vector as a vector, one value per layer, or a single value that applies to all layers.

- Agreed, taylor vector can be easier to use if it allows a single value for all hidden layers.

> Does forced_max_Q apply to the output of the layers if store_coeffs=TRUE? Should it?

- Yes, `forced_max_Q` applies to all hidden layers (provided that the product of Taylor orders from the start up to current layer is greater or equal than `forced_max_Q`, as explained above)

### Naming amd order proposal:
- `max_order`
- `keep_layers`
- `taylor_orders`
- `all_partitions`

**Comment by moralapablo** [comment]
Yes, I meant 3, will edit it now in the original comment.

**Comment by Enchufa2** [comment]
I would also

- invert `max_order` and `taylor_orders` in the plot function;
- drop the explicit specification of `taylor_orders` from the vignettes.
